project_id = "gvfbgxcetcamjdjvteji"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.daraja-stk-query]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.generate-voucher]
verify_jwt = false

[functions.revoke-voucher]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.cleanup-expired]
verify_jwt = false

[functions.sync-voucher-radius]
verify_jwt = false
