project_id = "gvfbgxcetcamjdjvteji"

[functions.mpesa-stk-push]
verify_jwt = true

[functions.daraja-stk-query]
verify_jwt = true

[functions.support-chat]
verify_jwt = false

[functions.generate-voucher]
verify_jwt = true

[functions.revoke-voucher]
verify_jwt = true

[functions.radius-auth]
verify_jwt = false
